# See http://www.appveyor.com/docs/appveyor-yml for many more options
environment:
  access_token:
    secure: r4AOJ+2A8L6Xa9RaE1hXIiRTz9IuDxl3pxFvXjFsP0Me2qDE64vXdWHiGxF2jE3Q

# Skip on updates to the readme.
# We can force this by adding [skip ci] or [ci skip] anywhere in commit message
skip_commits:
  message: /updated readme.*/

install:
  - cinst pester
  - ps: Install-PackageProvider -Name NuGet -Force
  - ps: Install-Module PsScriptAnalyzer -Force

build: false

test_script:
# Test with native PS version
#  - ps: . .\Tests\appveyor.pester.ps1
# Test with PS version 2
#  - ps: powershell.exe -version 2.0 -executionpolicy bypass -noprofile -file .\Tests\appveyor.pester.ps1
# Finalize pass - collect and upload results
#  - ps: . .\Tests\appveyor.pester.ps1 -Finalize

  - ps: $res = Invoke-Pester -Path ".\Tests" -OutputFormat NUnitXml -OutputFile TestsResults.xml -PassThru
  - ps: (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\TestsResults.xml))
  - ps: if ($res.FailedCount -gt 0) { throw "$($res.FailedCount) tests failed."}

on_success:
  - git config --global credential.helper store
  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
  - git config --global user.email "pezhore@gmail.com"
  - git config --global user.name "Brian Marsh"
  - git commit
  - git push origin :master